services:
  gatekeeper:
    build:
      context: .
      dockerfile: ./docker/uv/Dockerfile
    container_name: gatekeeper
    environment:
      EPIC_GAMES_EMAIL: ${EPIC_GAMES_EMAIL}
      EPIC_GAMES_PASSWORD: ${EPIC_GAMES_PASSWORD}
      EPIC_GAMES_LOCALE: ${EPIC_GAMES_LOCALE}
      EPIC_GAMES_COUNTRY: ${EPIC_GAMES_COUNTRY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    volumes:
      - gatekeeper_data:/app/data
    restart: unless-stopped

volumes:
  gatekeeper_data:
