services:
  gatekeeper:
#    build:
#      context: .
#      dockerfile: ./docker/uv/Dockerfile
    image: ghcr.io/nayetdet/gatekeeper:latest
    container_name: gatekeeper
    environment:
      CRONTAB: ${CRONTAB}
      EPIC_GAMES_EMAIL: ${EPIC_GAMES_EMAIL}
      EPIC_GAMES_PASSWORD: ${EPIC_GAMES_PASSWORD}
      EPIC_GAMES_LOCALE: ${EPIC_GAMES_LOCALE}
      EPIC_GAMES_COUNTRY: ${EPIC_GAMES_COUNTRY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    volumes:
      - gatekeeper_data:/app/data
    restart: unless-stopped # Set to "no" when no cron schedule is configured

volumes:
  gatekeeper_data:
