[project]
name = "rataria-epic-games"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "hcaptcha-challenger>=0.18.10",
    "playwright>=1.55.0",
    "requests>=2.32.5",
]
